using AuthECBackend.Models.Entities;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace AuthECBackend.Data
{
    public class ApplicationDbContext:IdentityDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
            
        }

        // This is neccessary, because we are using IdentityDbContext
        public DbSet<AppUser> AppUsers { get; set; }
        public DbSet<RefreshTokensEntity> RefreshTokens { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Configure the Id property as an identity column
            modelBuilder.Entity<RefreshTokensEntity>()
                .Property(rt => rt.Id)
                .ValueGeneratedOnAdd(); // This indicates that the Id will be generated by the database
        }
    }
}
